version: '3.8'

services:
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "3001:80"
     links:
       - db:db
     environment:
       MYSQL_USER: $MYSQLDB_USER
       MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
       MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
       PMA_HOST: db
     networks:
       - application