  version: '3.0'

services:
  mysql:
    image: mysql:8
    ports:
      - 3310:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=event_user
      - MYSQL_DATABASE=event_db
